package org.redhat.demo.brmsdemomarketing;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "BRMS_Demo_ActionType")
public class ActionType implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ACTIONTYPE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ACTIONTYPE_ID_SEQ", name = "ACTIONTYPE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Type")
   private java.lang.String type;

   @org.kie.api.definition.type.Label("Application")
   private java.lang.String app;

   @org.kie.api.definition.type.Label("Description")
   private java.lang.String desc;

   @org.kie.api.definition.type.Label("Cost")
   private Integer cost;

   public ActionType()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getApp()
   {
      return this.app;
   }

   public void setApp(java.lang.String app)
   {
      this.app = app;
   }

   public java.lang.String getDesc()
   {
      return this.desc;
   }

   public void setDesc(java.lang.String desc)
   {
      this.desc = desc;
   }

   public java.lang.Integer getCost()
   {
      return this.cost;
   }

   public void setCost(java.lang.Integer cost)
   {
      this.cost = cost;
   }

   public ActionType(java.lang.Long id, java.lang.String type,
         java.lang.String app, java.lang.String desc, java.lang.Integer cost)
   {
      this.id = id;
      this.type = type;
      this.app = app;
      this.desc = desc;
      this.cost = cost;
   }

}