package org.redhat.demo.brmsdemomarketing;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "BRMS_Demo_Capacity")
public class Capacity implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CAPACITY_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CAPACITY_ID_SEQ", name = "CAPACITY_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Budget")
   private Integer budget;

   @org.kie.api.definition.type.Label("MaxActionNumbers")
   private java.lang.Integer maxActionNumbers;

   @org.kie.api.definition.type.Label("Automatic")
   private java.lang.Boolean automatic;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("ActionTypes")
   private java.util.List<org.redhat.demo.brmsdemomarketing.ActionType> actionType;

   @org.kie.api.definition.type.Label("Comercial delegation")
   private java.lang.String regionFilter;

   @org.kie.api.definition.type.Label("Last MTO Prev")
   private java.lang.String lastMtoPrevFilter;

   @org.kie.api.definition.type.Label("localSubtype")
   private java.lang.String localSubtypeFilter;

   @org.kie.api.definition.type.Label("Assign")
   private java.lang.String assignation;

   @org.kie.api.definition.type.Label(value = "Budget Count")
   private java.lang.Integer budgetCount;

   @org.kie.api.definition.type.Label(value = "actionsCount")
   private java.lang.Integer actionsCount;

   public Capacity()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getMaxActionNumbers()
   {
      return this.maxActionNumbers;
   }

   public void setMaxActionNumbers(java.lang.Integer maxActionNumbers)
   {
      this.maxActionNumbers = maxActionNumbers;
   }

   public java.lang.Boolean getAutomatic()
   {
      return this.automatic;
   }

   public void setAutomatic(java.lang.Boolean automatic)
   {
      this.automatic = automatic;
   }

   public java.util.List<org.redhat.demo.brmsdemomarketing.ActionType> getActionType()
   {
      return this.actionType;
   }

   public void setActionType(
         java.util.List<org.redhat.demo.brmsdemomarketing.ActionType> actionType)
   {
      this.actionType = actionType;
   }

   public java.lang.Integer getBudget()
   {
      return this.budget;
   }

   public void setBudget(java.lang.Integer budget)
   {
      this.budget = budget;
   }

   public java.lang.String getRegionFilter()
   {
      return this.regionFilter;
   }

   public void setRegionFilter(java.lang.String regionFilter)
   {
      this.regionFilter = regionFilter;
   }

   public java.lang.String getLastMtoPrevFilter()
   {
      return this.lastMtoPrevFilter;
   }

   public void setLastMtoPrevFilter(java.lang.String lastMtoPrevFilter)
   {
      this.lastMtoPrevFilter = lastMtoPrevFilter;
   }

   public java.lang.String getLocalSubtypeFilter()
   {
      return this.localSubtypeFilter;
   }

   public void setLocalSubtypeFilter(java.lang.String localSubtypeFilter)
   {
      this.localSubtypeFilter = localSubtypeFilter;
   }

   public java.lang.String getAssignation()
   {
      return this.assignation;
   }

   public void setAssignation(java.lang.String assignation)
   {
      this.assignation = assignation;
   }

   public java.lang.Integer getBudgetCount()
   {
      return this.budgetCount;
   }

   public void setBudgetCount(java.lang.Integer budgetCount)
   {
      this.budgetCount = budgetCount;
   }

   public java.lang.Integer getActionsCount()
   {
      return this.actionsCount;
   }

   public void setActionsCount(java.lang.Integer actionsCount)
   {
      this.actionsCount = actionsCount;
   }

   public Capacity(
         java.lang.Long id,
         java.lang.Integer budget,
         java.lang.Integer maxActionNumbers,
         java.lang.Boolean automatic,
         java.util.List<org.redhat.demo.brmsdemomarketing.ActionType> actionType,
         java.lang.String regionFilter, java.lang.String lastMtoPrevFilter,
         java.lang.String localSubtypeFilter, java.lang.String assignation,
         java.lang.Integer budgetCount, java.lang.Integer actionsCount)
   {
      this.id = id;
      this.budget = budget;
      this.maxActionNumbers = maxActionNumbers;
      this.automatic = automatic;
      this.actionType = actionType;
      this.regionFilter = regionFilter;
      this.lastMtoPrevFilter = lastMtoPrevFilter;
      this.localSubtypeFilter = localSubtypeFilter;
      this.assignation = assignation;
      this.budgetCount = budgetCount;
      this.actionsCount = actionsCount;
   }

}