package org.redhat.demo.brmsdemomarketing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClientsToCampaign implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Clients")
   private java.util.List<org.redhat.demo.brmsdemomarketing.Client> clients;

   public ClientsToCampaign()
   {
   }

   public java.util.List<org.redhat.demo.brmsdemomarketing.Client> getClients()
   {
      return this.clients;
   }

   public void setClients(
         java.util.List<org.redhat.demo.brmsdemomarketing.Client> clients)
   {
      this.clients = clients;
   }

   public ClientsToCampaign(
         java.util.List<org.redhat.demo.brmsdemomarketing.Client> clients)
   {
      this.clients = clients;
   }

}